### ISSUE TITLE
concert is ok[ish], arte+7 is broken

### ISSUE THREAD

**Issue by ycardon** [Fra-Ktus/plex-arte#1]
concert : presents the list of shows then cannot play them
arte+7 : does not presents the list of shows

**Comment by Fra-Ktus** [comment]
Yes I saw that, will try to fix that this week end

**Comment by Fra-Ktus** [comment]
I posted a fix, french is back german is almost there, some videos plays some don't

**Comment by ycardon** [comment]
hey thank you :)

**Comment by Fra-Ktus** [comment]
I just fixed it, can you try it ?

**Comment by ycardon** [comment]
works very well now :)

**Comment by Fra-Ktus** [comment]
Concert is still ok but the other part is broken at the moment and I will try to fix it quickly
